# Generated by Django 5.2.17 on 2026-08-09 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        ("organizations", "0001_initial"),
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenanceschedule",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedules",
                to="tickets.category",
            ),
        ),
        migrations.AddField(
            model_name="maintenanceschedule",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_schedules",
                to="organizations.organization",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="asset",
            unique_together={("organization", "asset_code")},
        ),
    ]
