# Generated by Django 5.2.17 on 2026-08-09 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("status_change", "Status Changed"),
                            ("assign", "Assigned"),
                            ("unassign", "Unassigned"),
                            ("login", "Logged In"),
                            ("logout", "Logged Out"),
                            ("permission_change", "Permission Changed"),
                            ("priority_change", "Priority Changed"),
                            ("comment_add", "Comment Added"),
                            ("attachment_add", "Attachment Added"),
                            ("attachment_delete", "Attachment Deleted"),
                            ("reopen", "Reopened"),
                            ("close", "Closed"),
                            ("verify", "Verified"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "object_id",
                    models.PositiveBigIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                ("object_repr", models.CharField(blank=True, max_length=500)),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("message", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["organization", "timestamp"],
                        name="audit_log_organiz_1cfd1d_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="audit_log_user_id_835db7_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="audit_log_content_10f046_idx",
                    ),
                ],
            },
        ),
    ]
