# Generated by Django 5.2.17 on 2026-08-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Created"),
                    ("update", "Updated"),
                    ("delete", "Deleted"),
                    ("status_change", "Status Changed"),
                    ("assign", "Assigned"),
                    ("unassign", "Unassigned"),
                    ("login", "Logged In"),
                    ("logout", "Logged Out"),
                    ("permission_change", "Permission Changed"),
                    ("priority_change", "Priority Changed"),
                    ("comment_add", "Comment Added"),
                    ("attachment_add", "Attachment Added"),
                    ("attachment_delete", "Attachment Deleted"),
                    ("reopen", "Reopened"),
                    ("close", "Closed"),
                    ("verify", "Verified"),
                    ("bulk_action", "Bulk Action"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
