# Generated by Django 5.2.17 on 2026-08-09 18:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("building", "Building"),
                    ("block", "Block / Wing"),
                    ("floor", "Floor"),
                    ("room", "Room / Unit"),
                    ("area", "Area / Zone"),
                    ("outdoor", "Outdoor / Grounds"),
                    ("hostel_block", "Hostel Block"),
                    ("hostel_floor", "Hostel Floor"),
                    ("hostel_room", "Hostel Room"),
                    ("common_area", "Common Area"),
                    ("washroom", "Washroom / Bathroom"),
                    ("lab", "Laboratory"),
                    ("workshop", "Workshop"),
                ],
                default="room",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ResidentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room_number",
                    models.CharField(
                        blank=True, help_text="Display room number/label", max_length=20
                    ),
                ),
                (
                    "bed_number",
                    models.CharField(
                        blank=True,
                        help_text="Bed letter/number within room",
                        max_length=10,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("check_in_date", models.DateField(blank=True, null=True)),
                ("check_out_date", models.DateField(blank=True, null=True)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=150),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="residents",
                        to="organizations.organization",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"location_type__in": ["hostel_room", "room"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="residents",
                        to="organizations.location",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resident_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resident Profile",
                "verbose_name_plural": "Resident Profiles",
                "db_table": "organizations_resident_profile",
            },
        ),
    ]
