# Generated by Django 5.2.17 on 2026-08-09 13:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tickets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("ticket_created", "Ticket Created"),
                            ("ticket_assigned", "Ticket Assigned"),
                            ("ticket_reassigned", "Ticket Reassigned"),
                            ("ticket_status_changed", "Status Changed"),
                            ("ticket_priority_changed", "Priority Changed"),
                            ("comment_added", "Comment Added"),
                            ("sla_approaching", "SLA Approaching"),
                            ("sla_breached", "SLA Breached"),
                            ("resolution_submitted", "Resolution Submitted"),
                            ("ticket_reopened", "Ticket Reopened"),
                            ("ticket_closed", "Ticket Closed"),
                            ("maintenance_scheduled", "Maintenance Scheduled"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("link", models.CharField(blank=True, max_length=500)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "notifications_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="notificatio_recipie_4e3567_idx",
                    ),
                    models.Index(
                        fields=["recipient", "created_at"],
                        name="notificatio_recipie_f39341_idx",
                    ),
                ],
            },
        ),
    ]
